Trying to fix `aboutanime`
The-4th-Hokage/yondaime-hokage pull request #725
Opened 2022-10-24 06:03 UTC by eitozx

Signed-off-by: Eito <iameitozx@gmail.com>

## Summary
This is suppose to fix #687 . 
Honestly saying, I think this should fix, has this been tested? sorry i couldn't, I asked u for the cog file but it turns out that it is importing various stuff from other files as well. If you can merge this, fine, or otherwise I suggest you to make a guide for contributors please lmao 💀 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-25 06:23 UTC, Chii-Onan commented
Hi, I'd just like to address a couple of things.

> sorry i couldn't, I asked u for the cog file but it turns out that it is importing various stuff from other files as well. If you can merge this, fine, or otherwise I suggest you to make a guide for contributors please lmao 💀

I don't really think it would've hard to find a command with crtl + f but kk.

Next, this PR doesn't do much... In the try and except, we won't always error because the anime wasn't found. There can be a multitude of reasons and as such this message is very misleading, if that makes sense.

2022-10-25 09:02 UTC, eitozx commented
> Next, this PR doesn't do much... In the try and except, we won't always error because the anime wasn't found. There can be a multitude of reasons and as such this message is very misleading, if that makes sense.

I find it hard to start the bot without the guide to set up the bot. That's the simple reason cuz there are many changes in set-up since last year. And i agree with your point in terms of error. Either way, I don't mind making changes whereever required if i get the set-up guide

2022-10-26 18:13 UTC, Dhruvacube commented
> > Next, this PR doesn't do much... In the try and except, we won't always error because the anime wasn't found. There can be a multitude of reasons and as such this message is very misleading, if that makes sense.
> 
> I find it hard to start the bot without the guide to set up the bot. That's the simple reason cuz there are many changes in set-up since last year. And i agree with your point in terms of error. Either way, I don't mind making changes whereever required if i get the set-up guide

yeah going to set up that only!

2022-10-26 18:14 UTC, Dhruvacube requested changes

2022-10-26 18:14 UTC, Dhruvacube commented on minato_namikaze/cogs/anime_and_vocaloids/anime_and_waifu.py
> +        except:
please here do change this to this

2022-10-26 18:14 UTC, Dhruvacube commented on minato_namikaze/cogs/anime_and_vocaloids/anime_and_waifu.py
> +        except:
```python
except ValueError:
```

2022-10-26 18:35 UTC, Dhruvacube approved these changes

2022-10-26 18:36 UTC, merged